[package]
name = "project_quarry"
version = "0.0.104"

[dependencies]
rust-embed = "4.4.0"
conrod_core = "0.65.0"
conrod_winit = "0.65.0"
conrod_glium = "0.65.0"
glium = "0.23.0"
winit = "*"
git2 = "0.9.1"
