[package]
name = "ssf_installer"
version = "0.0.204"
authors = ["SFort"]

[dependencies]
rust-embed = "4.4.0"
base64 = "0.10.1"
conrod_core = "0.65.0"
conrod_winit = "0.65.0"
conrod_glium = "0.65.0"
glium = "0.23.0"
git2 = "0.9.1"
winit = "0.18.1"
