[package]
name = "projectQuarry"
version = "0.0.1"

[dependencies]
rust-ini = "0.13.0"

[target.'cfg(any(unix, macos))'.dependencies.cursive]
version = "0.10.0"
default-features = false
features = ["termion-backend"]
